version: 2.1

jobs:
  build-and-test:
    parameters:
      python_version:
        description: "Python version to test against"
        default: "3.10.4"
        type: string
    docker:
      - image: cimg/python:<< parameters.python_version >>
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-<< parameters.python_version >>-{{ checksum "poetry.lock" }}
      - run:
          name: install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -U pip poetry
            poetry install
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-<< parameters.python_version >>-{{ checksum "poetry.lock" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest isabelle_client
      - run:
          name: run linters
          command: |
            . venv/bin/activate
            flake8 isabelle_client examples
            pylint isabelle_client examples
      - run:
          name: run type checks
          command: |
            . venv/bin/activate
            mypy isabelle_client examples
      - run:
          name: upload data to codecov
          command: |
            bash <(curl -s https://codecov.io/bash) -X gcov -X coveragepy
      - store_artifacts:
          path: build
      - store_test_results:
          path: test-results

workflows:
  workflow:
    jobs:
      - build-and-test:
          python_version: "3.7.13"
      - build-and-test:
          python_version: "3.8.13"
      - build-and-test:
          python_version: "3.9.12"
      - build-and-test:
          python_version: "3.10.4"
